{
 "title": "Deal with time",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Deals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    value\r\nFROM prom_metric.\"Nominal\" srt\r\nWHERE  --\"time\" > now() - INTERVAL '1 days'\r\n     $__timeFilter(\"time\")\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Deals Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    value\r\nFROM prom_metric.\"Nominal\" srt\r\nWHERE  --\"time\" > now() - INTERVAL '1 days'\r\n     $__timeFilter(\"time\")\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Norminal distrib (hour sum) | bucket size 5B",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 hour', time) AS time,\r\n    SUM(value) sum_nominal\r\nFROM prom_metric.\"Nominal\" srt\r\nWHERE -- symbol = '$symbol' AND\r\n     --\"time\" > now() - INTERVAL '3 days'\r\n       $__timeFilter(\"time\")\r\nGROUP BY time_bucket('1 hour', time)\r\norder by time;"
    }
   ]
  },
  {
   "title": "[20, 6000] 5 buckets histogram",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT val(\"StrategyName_id\") AS strategy, histogram(value, 20, 6000, 5)\r\nFROM prom_metric.\"Nominal\"\r\nwhere --\"time\" > now() - INTERVAL '1 days'\r\n      $__timeFilter(\"time\")\r\nGROUP BY \"StrategyName_id\"\r\n;"
    }
   ]
  },
  {
   "title": "Strat, VenueCategory",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n  val(\"StrategyName_id\") as \"Strategy\",\r\n  val(\"VenueCategory_id\") as \"VenueCategory\",\r\n  sum(value)\r\nFROM \"Nominal\"\r\nWHERE\r\n $__timeFilter(\"time\")  \r\n  group by \"StrategyName_id\",\"VenueCategory_id\""
    }
   ]
  },
  {
   "title": "Strategy, VenueType",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n  val(\"StrategyName_id\") as \"Strategy\",\r\n  val(\"VenueType_id\") as \"VenueType\",\r\n  sum(value)\r\nFROM \"Nominal\"\r\nWHERE\r\n $__timeFilter(\"time\")  \r\n  group by \"StrategyName_id\",\"VenueType_id\"\r\n  order by sum(value) desc"
    }
   ]
  },
  {
   "title": "Nominal Percentile Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select\r\n       --strat,\r\n       bucket,\r\n       round(avg(value)::numeric, 0) avg_in_bucket,\r\n       round(min(value)::numeric, 0) min_in_bucket,\r\n       round(max(value)::numeric, 0) max_in_bucket,\r\n       count(0)\r\nfrom (select val(\"StrategyName_id\") strat,\r\n             value,\r\n             ntile(10) over (order by value) as bucket\r\n      from prom_metric.\"Nominal\"\r\n      where\r\n          --val(\"StrategyName_id\") = 'Hit' and\r\n          \"time\" > now() - INTERVAL '1 days'\r\n         --AND $__timeFilter(\"time\")\r\n     ) as foo\r\ngroup by /*strat,*/ bucket\r\norder by bucket;"
    }
   ]
  },
  {
   "title": "Nominal Percentile",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select\r\n       --strat,\r\n       to_char(bucket*10, '999') || '%' AS percentile_label,\r\n       round(avg(value)::numeric, 0) value--,\r\n       --round(min(value)::numeric, 0) min_in_bucket,\r\n       --round(max(value)::numeric, 0) max_in_bucket,\r\n       --count(0)\r\nfrom (select --val(\"StrategyName_id\") strat,\r\n             value,\r\n             ntile(10) over (order by value) as bucket\r\n      from prom_metric.\"Nominal\"\r\n      where\r\n          --val(\"StrategyName_id\") = 'Hit' and\r\n          \"time\" > now() - INTERVAL '1 days'\r\n         --AND $__timeFilter(\"time\")\r\n     ) as foo\r\ngroup by /*strat,*/ bucket\r\norder by bucket;"
    }
   ]
  }
 ]
}